Provider:
---------

CREATE DATABASE IF NOT EXISTS SALESDB;


CREATE SCHEMA IF NOT EXISTS SALESDB.PUBLIC;

CREATE OR REPLACE TABLE SALESDB.PUBLIC.SALES (
    sale_id INT,
    customer_id INT,
    amount NUMBER(10,2),
    sale_date DATE
);

INSERT INTO SALESDB.PUBLIC.SALES VALUES
    (1, 101, 250.75, '2025-01-10'),
    (2, 102, 120.00, '2025-01-11'),
    (3, 101, 89.50,  '2025-01-12'),
    (4, 103, 560.00, '2025-01-13'),
    (5, 104, 42.99,  '2025-01-14');

    SELECT * FROM SALESDB.PUBLIC.SALES;


    CREATE OR REPLACE SHARE salesshare;

GRANT USAGE ON DATABASE SALES_DB TO SHARE salesshare;
GRANT USAGE ON SCHEMA SALES_DB.PUBLIC TO SHARE salesshare;
GRANT SELECT ON TABLE SALES_DB.PUBLIC.SALES TO SHARE salesshare;

ALTER SHARE salesshare ADD ACCOUNTS = LUIOTBY.PXB63567;


ALTER SHARE salesshare REMOVE ACCOUNTS = LUIOTBY.PXB63567;
REVOKE SELECT ON TABLE SALESDB.PUBLIC.SALES FROM SHARE salesshare;
REVOKE USAGE ON SCHEMA SALESDB.PUBLIC FROM SHARE salesshare;
REVOKE USAGE ON DATABASE SALESDB FROM SHARE salesshare;

Consumer:
---------
SHOW SHARES;

CREATE DATABASE salesdbfromshare FROM SHARE VICLXLD.PVB41595.salesshare;

SELECT * FROM salesdbfromshare.PUBLIC.SALES;
