CREATE WAREHOUSE IF NOT EXISTS SNOWPARK_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS SNOWPARK_DB;

CREATE SCHEMA IF NOT EXISTS SNOWPARK_DB.SNOWPARK_SCHEMA;

CREATE TABLE IF NOT EXISTS SNOWPARK_DB.SNOWPARK_SCHEMA.ORDERS (
    ORDER_ID    INT,
    CUSTOMER    STRING,
    AMOUNT      FLOAT,
    STATUS      STRING,
    REGION      STRING
);


INSERT INTO SNOWPARK_DB.SNOWPARK_SCHEMA.ORDERS VALUES
    (1, 'Alice',   150.00, 'ACTIVE',   'WEST'),
    (2, 'Bob',      80.50, 'INACTIVE', 'EAST'),
    (3, 'Charlie', 200.00, 'ACTIVE',   'WEST'),
    (4, 'Diana',    45.00, 'ACTIVE',   'NORTH'),
    (5, 'Eve',     310.00, 'INACTIVE', 'SOUTH'),
    (6, 'Frank',   175.00, 'ACTIVE',   'EAST'),
    (7, 'Grace',    95.00, 'ACTIVE',   'NORTH');



SELECT * FROM SNOWPARK_DB.SNOWPARK_SCHEMA.ORDERS;

SELECT * FROM SNOWPARK_DB.SNOWPARK_SCHEMA.REGION_SUMMARY;


CREATE OR REPLACE FUNCTION SNOWPARK_DB.SNOWPARK_SCHEMA.CALCULATE_DISCOUNT(amount FLOAT)
RETURNS FLOAT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'run'
AS
$$
def run(amount):
    if amount > 200:
        return amount * 0.2
    else:
        return amount * 0.1
$$;

SELECT 
    ORDER_ID,
    CUSTOMER,
    AMOUNT,
    STATUS,
    REGION,
    SNOWPARK_DB.SNOWPARK_SCHEMA.CALCULATE_DISCOUNT(AMOUNT) AS DISCOUNT
FROM SNOWPARK_DB.SNOWPARK_SCHEMA.ORDERS;



SELECT * FROM SNOWPARK_DB.SNOWPARK_SCHEMA.REGION_SUMMARY_SP;
